global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'collector'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ["collector:8080"]
        labels:
          group: 'collector'
